function MedicationView(patient) {
  return `
  <div class="header-bar">
    <div class="fw-semibold">Medication</div>
  </div>
  <div class="container py-4">
    <div class="card-glass p-4">
      <div class="mb-2 text-secondary">Prescribed by your doctor</div>
      <div style="white-space:pre-wrap;">${
        patient.medication || "No medication yet."
      }
        
      </div>
     <button class="btn btn-outline-dark" onclick="printMedicationReport('${patient.id}')">🧾 Print Medication
        </button>

    </div>
  </div>`;
}

function renderMedication() {
  const session = getSession();
  if (!session?.patientId) {
    document.getElementById("content").innerHTML =
      '<div class="p-4">No medication found.</div>';
    return;
  }
  const patient = getPatientById(session.patientId);
  const root = document.getElementById("content");  
  root.innerHTML = MedicationView(patient);
}

function printMedicationReport(patientId) {
  const p = getPatientById(patientId);
  if (!p) return alert('Patient not found');

  // Prepare HTML content for printable page
  const html = `
  <html>
  <head>
    <title>Medication Report - ${p.name}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
      body { font-family: 'Segoe UI', sans-serif; margin: 40px; }
      .header { text-align: center; border-bottom: 2px solid #20c997; padding-bottom: 10px; margin-bottom: 30px; }
      .title { font-size: 24px; font-weight: bold; color: #20c997; }
      .section-title { font-weight: 600; font-size: 18px; color: #111; margin-top: 30px; }
      .info { font-size: 15px; }
      .med-box { border: 1px dashed #20c997; padding: 12px; margin-top: 10px; white-space: pre-wrap; }
      .footer { text-align: center; margin-top: 50px; color: #777; font-size: 13px; }
      @media print { button { display: none; } }
    </style>
  </head>
  <body>
    <div class="header">
      <div class="title">Medora Health - COVID</div>
      <div>Medication Report</div>
    </div>
    <div class="info">
    <div style="text-align:center; margin-bottom:20px;">
  <img src="${p.photo || 'img/default-user.png'}" width="120" height="120" class="rounded-circle border" alt="Patient Photo">
</div>
      <strong>Patient Name:</strong> ${p.name}<br>
      <strong>Phone:</strong> ${p.phone}<br>
      <strong>Age:</strong> ${p.age} | <strong>Gender:</strong> ${p.gender}<br>
      <strong>State:</strong> ${p.state}<br>
      <strong>Health Status:</strong> ${p.status}<br>
      <strong>Relative:</strong> ${p.relative || '-'}<br>
      <strong>Last Updated:</strong> ${new Date(p.updatedAt).toLocaleString()}
    </div>

    <div class="section-title">Medication Details</div>
    <div class="med-box">${p.medication || 'No medication prescribed yet.'}</div>

    <div class="footer">
      Generated by Medora Health System<br>
      Doctor Signature: ____________________
    </div>
    <script>
      window.print();
    </script>
  </body>
  </html>
  `;

  // Open print view
  const newWin = window.open('', '_blank');
  newWin.document.write(html);
  newWin.document.close();
}
